apiVersion: v1
kind: Secret
metadata:
  name: ghr-secret
  labels:
    {{- include "ghr.labels" . | nindent 4 }}
type: Opaque
data:
  GH_TOKEN: {{ default "" .Values.ghr.github_token | b64enc | quote }}
