# This is a basic workflow to help you get started with Actions

name: AKS Self Hosted Runner

# Controls when the workflow will run
on: workflow_dispatch

env:
  # Remember to convert to secret variables before merging
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  CLUSTER_NAME: githubrunner
  GITHUB_REPO_OWNER: tristanang
  GITHUB_REPO_NAME: aks-github-runner
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Runs a single command using the runners shell
      - name: Run setup.sh
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
