# This is a basic workflow to help you get started with Actions

name: AKS Self Hosted Runner

# Controls when the workflow will run
on: [push, workflow_dispatch]

env:
  # Remember to convert to secret variables before merging
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  REGION: eastus2
  CLUSTER_NAME: githubrunner
  STORAGE_ACCOUNT_NAME: runnerstorage6594
  GITHUB_REPO_OWNER: tristanang
  GITHUB_REPO_NAME: aks-github-runner
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Runs a single command using the runners shell
      - name: Run setup.sh
        id: setup_storage
        run: |
          CONTAINER_NAME=$(echo "${CLUSTER_NAME}" | tr '[:upper:]' '[:lower:]')tfstate
          az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob
          ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME --account-key $ACCOUNT_KEY
          echo "::set-output name=container_name::$CONTAINER_NAME"
          echo "::set-output name=account_key::$ACCOUNT_KEY"
      - uses: tristanang/aks_create_action@main
        with:
          CLUSTER_NAME: ${{ env.CLUSTER_NAME }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          STORAGE_ACCOUNT_NAME: ${{ env.STORAGE_ACCOUNT_NAME }}
          STORAGE_CONTAINER_NAME: ${{ steps.setup_storage.outputs.container_name }}
          STORAGE_ACCESS_KEY: ${{ steps.setup_storage.outputs.account_key }}
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
          ACTION_TYPE: create
          CREATE_ACR: true
